Sprint 2/step 2
Kisa6996/react-burger pull request #4
Opened 2023-05-25 06:23 UTC by Kisa6996

2023-05-25 06:55 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Раздельное хранение булок и ингредиентов
- Хорошая организация хранилища
- Для каждого запроса созданы все необходимые экшены
- Обозначили область конструктора - куда переносить ингредиенты

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У вас в запросе на номер заказа передаются объекты ингредиентов, а не строки.

<img width="1438" alt="Снимок экрана 2023-05-25 в 09 47 09" src="https://github.com/Kisa6996/react-burger/assets/60173362/5a83e887-6962-46f0-b62c-dcd779d3f918">

- Необходимо дописать некоторые `propTypes`
- если экшен не выполняет сайдэффектов, то не должна диспатчится функция и пропускатсья через thunk
- при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене
- Не совсем корректно определяется - какой таб подсвечивать

<img width="468" alt="Снимок экрана 2023-05-25 в 09 53 59" src="https://github.com/Kisa6996/react-burger/assets/60173362/004a8d8b-1f40-49fb-93da-45ebd7873d17">

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-25 06:55 UTC, andryxxa93 commented on src/components/border-burger/border-burger.js
> +BorderBurger.propTypes = {
**Необходимо исправить**
Тут не хватает пропа `children `

2023-05-25 06:55 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +  const { flag } = useSelector((state) => state.burgerReducer);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-05-25 06:55 UTC, andryxxa93 commented on src/components/cards/cards.js
> +Cards.propTypes = {
**Необходимо исправить**
Тут не хватает пропа `id`

2023-05-25 06:55 UTC, andryxxa93 commented on src/services/actions/burger.js
> +export function updateConsrtuctor(item) {
**Надо исправить**

не совсем верно организован диспатчи простых экшенов, не требующих сайд эффектов.

Если действие не требует запросов к серверу или каких то побочных эффектов, то нужно дисптчить просто объект экшена, а не функцию

Например, как сделано сейчас:

Описана функция

```
export const moveConstructorItem = (dragIndex, hoverIndex) => (dispatch) => {
	dispatch({
		type: MOVE_CONSTRUCTOR_ITEM,
		dragIndex,
		hoverIndex,
	});
};

dispatch(moveConstructorItem(dragIndex, hoverIndex)); //будет задиспатчена функция
```

Если присмотреться, то в коде есть два dispatch. Что при этом происходит:

мы диспатчик функцию => thunk перехватывает функцию => thunk выполняет функцию => функция сама диспатчит экшен => экшен попадает в редьюсер

В случае экшена не требующего сайдэффектов 2, 3 и 4 звено в цепочке лишние, т.к. не нужно пропускать простые экшены через thunk

Как должно быть:

```
//такая функция называется action creator - она принимает данные и возвращает объект (а не функцию)
export const moveConstructorItem = (dragIndex, hoverIndex) => ({
	type: MOVE_CONSTRUCTOR_ITEM,
	dragIndex,
	hoverIndex,
});

dispatch(moveConstructorItem(dragIndex, hoverIndex));
```

Но в этом случае будет задиспатчен объект
при этом не будет в цепочке обработки экшена лишних шагов, экшен не будет перехвачен thunk т.к. является объектом, а не функцией, а попадет сразу в редюсер

Нужно исправить это замечание для всех подобных мест в проекте, где при диспатче нужно просто передать экшен в редьюсер, а не выполнять сайдэффекты.

2023-05-25 06:55 UTC, andryxxa93 commented on src/services/reducers/burger.js
> +            uuid: uuidv4(),
**Надо исправить**

редьюсер должен быть чистой функции, сейчас при каждом вызове добавления ингредиента результат будет отличаться, даже если стейт и экшен одинаковые - будет генерироваться каждый раз новый id,  при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене, а не генерировать в редьюсере. Иначе это делает редьюсер не чистой функцией, что нарушает правило редьюсеров

2023-05-25 07:03 UTC, Kisa6996 commented
Таб подсвечивает зону видимости 
, там видны соусы сразу.

2023-05-25 07:04 UTC, Kisa6996 commented
Не понимаю тогда какое решение взять

2023-05-26 05:54 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-29 05:05 UTC, merged